Allow observation files with a single variable in joint assimilation
ealonsogzl/MuSA pull request #12
Opened 2023-07-04 14:15 UTC by mmazzolini

Hi Esteban.. 

this is a very rough proposal for allowing observation files with a single observation. Feel free to discard it.

Cheers.
Marco.

PS: I debugged also this line https://github.com/ealonsogzl/MuSA/blob/76639db4ffaea7053860642d1589ac2fbeaa3c88/modules/internal_fns.py#L61 . 
I don't understand how that was working.. shouldn't observations have different column counting than df_state ? I don't get how that was working preciously.

2023-07-04 14:30 UTC, ealonsogzl requested changes
Well seen that problem. It has not caused problems yet because no more than two observations have been assimilated since it was implemented. 
please resolve this bare except comments before merging.
Regards

2023-07-04 14:30 UTC, ealonsogzl commented on modules/internal_fns.py
> +            except:
please do not use bare excepts. Add the exceptions you expect to find. If there was a problem in a corrupt netcdf for example, we want MuSA to throw an exception.

2023-07-04 14:30 UTC, ealonsogzl commented on modules/spatialMuSA.py
> +            except:
Same here, bare except

2023-07-06 20:02 UTC, mmazzolini commented
Hi @ealonsogzl 
Removed the try/except blocks and a couple of print statements..

However, if there are files with none of the obs_var_names present no exception is raised.
I guess it's possible to write that error in the obs_array function.

But we would need to invert the order of the for loops in the obs_array function:  it's necessary to check in the obs files both the obs_var before raising the error. 
This is not possible now if the first for loop is through the obs_var_names. We would need to loop through the files first and through the obs_var_names afterwards.

If you want I can try to implement & test in the future but for now I think this is acceptable. Let me know what you think.

Cheers,
Marco.

2023-07-07 08:32 UTC, merged

2023-07-07 08:38 UTC, ealonsogzl commented
great, thank you very much Marco.
If there are no observations in any variable MuSA in a file should not throw an exception, if it did we would not be able to activate the spatial module in case of all observation times in a cell do not store any observations (like in your recent runs). The filters are ready to just keep the prior if there is nothing to assim.

For my part, I don't think I will use this capability, as with my routines I find it much more comfortable to prepare the observations as before, plus I find it less error prone. So feel free to propose here the changes that make your life easier :)

cheers